-- Reconcile AuditAction enum with Prisma schema (safe IF NOT EXISTS for drifted prod DBs)
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEMBER_REGISTERED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEMBER_CHECK_IN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MEASUREMENT_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_VOIDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PAYMENT_RECORDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_LOGIN_FAILED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACCESS_DENIED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'API_ERROR';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUDIT_LOG_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MESSAGE_REPORTED';
